### ISSUE TITLE
Can't connect to MCX8000

### ISSUE THREAD

**Issue by rubnixble** [icedream/go-stagelinq#20]
No matter what I've tried, I can't get it to connect to an MCX8000 controller.

Keep getting this error:
![image](https://user-images.githubusercontent.com/121902159/210527313-ade4092c-8207-4455-89ae-889c71ab57f1.png)

**Comment by dzelionis** [comment]
MCX8000 is a completely different type of gear (legacy), I  do not think that its running Linux underhood...anyway that's expected to not work as it is not comaptible

**Comment by icedream** [comment]
This already [confused other people](https://community.enginedj.com/t/confusion-regarding-stagelinq-and-mcx8000/10109) before, but yeah, unfortunately the MCX8000 is not compatible.
