### ISSUE TITLE
Didn't work with two SC5000s

### ISSUE THREAD

**Issue by chrisle** [icedream/go-stagelinq#3]
So we tested this with two SC5000s.

go-stagelinq found the two decks (with two IP addresses). 
Loading a song from USB stick on deck 1, it would get the data correctly and printf'd it.
However, loading a song on deck 2, it wouldn't show up.

In the log, we first see the initial state of both decks, but from that point forward only actions on deck 1 where the USB stick would be printf'd. Deck 2 never printf'd anything from that point forward.

**Comment by icedream** [comment]
I wonder if we're dealing with minor differences in the network protocol here between the SC5000 and the Prime 4, unfortunately I don't have the hardware to test this out. Are you using the example app code from this repository to try this or what are the steps to reproduce this?

**Comment by icedream** [comment]
Closing this as can't replicate and no feedback delivered.
